### ISSUE TITLE
Question about "Lighting 1 switch" section in README

### ISSUE THREAD

**Issue by mwittig** [Timvdv/pimatic-rfxcom#3]
I don't understand the last part of the README starting with "If you want to work you have do add this piece of code to the file at the bottom:". Why should the use add code?

**Comment by Timvdv** [comment]
Because there is a function missing in the RFXCom library which controls the Lighting1 devices. To be able to control those device you need to add the function.

I was about to create a pull request but my focus went on other stuff :)
and I only have one Lighting 1 device which is not powered on so I never took the time to fix it
But you're right this should be implemented the right way.

**Comment by mwittig** [comment]
Thanks for the clarification and swift reply! May be things have also improved with rfxcom@0.8.0. The following commit looks promising as far as I can tell. https://github.com/rfxcom/node-rfxcom/commit/9cf965faa9748290f0a8d34baec75a0fe2b215d4

**Comment by Timvdv** [comment]
I created a pull request to the RFXCom lib and they accepted, so I removed the piece of code from the bottom part of the README because it is no longer needed :)!
