### ISSUE TITLE
Add lighting5 and security1 to rfxcom

### ISSUE THREAD

**Issue by hempie01** [Timvdv/pimatic-rfxcom#4]
Tim,
is it possible to add lighting5 and security1 on plugin pimatic-rfxcom?
these are the action Promax switch and the visonic PIR motion detector.

regards

**Comment by Timvdv** [comment]
Hey Hempie,

Well, this is a bit difficult. When I add more lighting types the RFXCom gets less accurate (which I don't want), so next option would be to add some sort of lighting code options. Or.. just add lighting 5 and hope for the best. Anyways.. It will take some time and I can't be sure if it's going to work because I down own these devices. I'll look into this when I have some time. 

Tim

**Comment by hempie01** [comment]
Tim,
I use the rfxcom (Lighting 2) for a year and it works fantastic.
There are 6 lights that i switch at once, via a rule(sunset/sunrise).
The Promax Action switch are 10 euro, for 3 pieces...much cheaper than the kaku.
Thanks for your quick reply.

greetings
